export const ADD_TOKEN = 'ADD_TOKEN';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const ADD_BREWERIES = 'ADD_BREWERIES';
export const BREWERIES_LOADING = 'BREWERIES_LOADING';
export const BREWERIES_FAILED = 'BREWERIES_FAILED';